app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError, Length
from flask_babel import lazy_gettext as _l
from flask_babel import _

from app.models import User


class EditProfileForm(FlaskForm):
    """Login form for a User"""

    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = StringField(_l('About me'), validators=[Length(min=0, max=128)])
    submit = SubmitField(_l('Save'))

    def __init__(self, original_username, *args, **kwargs):
        """Adds {original_username} field to compare original username and entered one in profile edit form"""

        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        """Checks whether edited username already exists. Raises error in case of existence"""

        if username.data != self.original_username and User.query.filter_by(username=username.data).first():
            raise ValidationError(_('Please use a different username.'))


class SubmitForm(FlaskForm):
    """Form for user to follow or unfollow"""

    submit = SubmitField(_l('Submit'))


class PostForm(FlaskForm):
    """Form for post creating"""

    text = StringField(_l('Your post'), validators=[Length(min=0, max=256)])
    submit = SubmitField(_l('Save'))


class SearchForm(FlaskForm):
    """Form for searching posts"""

    text = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'meta' not in kwargs:
            kwargs['meta'] = {'csrf': False}
        super().__init__(*args, **kwargs)

app/messages/forms.py
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class MessageForm(FlaskForm):
    """Form for sending private messages"""

    message = TextAreaField(_l('Message'), validators=[DataRequired(), Length(min=0, max=256)])
    submit = SubmitField(_l('Send'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import forms, routes

app/main/routes.py
from datetime import datetime
from langdetect import detect, LangDetectException
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from flask_babel import _
from flask import g
from flask_babel import get_locale
from flask import current_app as app

from app import db
from app.main import bp
from app.main.forms import EditProfileForm, SubmitForm, PostForm, SearchForm
from app.models import User, Post, Notification
from app.translate import translate


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    """Home Page: displays posts from users you follow with pagination"""

    form = PostForm()
    if form.validate_on_submit():

        try:
            language = detect(form.text.data)
        except LangDetectException:
            language = ''

        post = Post(body=form.text.data, user_id=current_user.id, language=language)
        db.session.add(post)
        db.session.commit()

    page = request.args.get('page', 1, type=int)
    posts = current_user.get_posts_from_followed_users().paginate(page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) if posts.has_prev else None

    return render_template('main/index.html', title=_('Home'), posts=posts.items, form=form, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/explore')
@login_required
def explore():
    """Explore Page: displays posts from all the users paginated and ordered by timestamp"""

    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.explore', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) if posts.has_prev else None

    return render_template('main/index.html', title=_('Explore'), posts=posts.items, next_url=next_url,
                           prev_url=prev_url)


@bp.route('/translate', methods=['POST'])
@login_required
def translate_post():
    """View for posts translation. Returns {'text': <translated text>} dictionary"""

    return jsonify({
        'text': translate(request.form['text_to_translate'], request.form['source_language'],
                          request.form['destination_language'])
    })


@bp.route('/user_profile/<username>')
@login_required
def user_profile(username):
    """User Profile Page: displays common info of the user"""

    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.paginate(page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.user_profile', username=user.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.user_profile', username=user.username, page=posts.prev_num) if posts.has_prev else None
    form = SubmitForm()

    return render_template('main/user_profile.html', title=_('User Profile'), user=user, posts=posts.items, form=form,
                           prev_url=prev_url, next_url=next_url)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    """Edit Profile Page: allows to make changes to username and about_me field"""

    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash(_('Your changes have been saved.'))
        return redirect(url_for('main.user_profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me

    return render_template('main/edit_profile.html', title=_('Edit Profile'), form=form)


@bp.route('/follow/<username>', methods=['GET', 'POST'])
@login_required
def follow(username):
    """View to follow the user. Called by submit button on user profile page"""

    form = SubmitForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()

        if not user:
            flash(_('User %(username)s not found.', username=username))
            return redirect(url_for('main.index'))

        if user == current_user:
            flash(_('You cannot follow yourself!'))
            return redirect(url_for('main.user_profile', username=username))

        current_user.follow(user)
        db.session.commit()
        flash(_('You are following %(username)s!', username=username))
        return redirect(url_for('main.user_profile', username=username))

    return redirect(url_for('main.index'))


@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    """View to unfollow the user. Called by submit button on user profile page"""

    form = SubmitForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()

        if not user:
            flash(_('User %(username)s not found.', username=username))
            return redirect(url_for('main.index'))

        if user == current_user:
            flash(_('You cannot unfollow yourself!'))
            return redirect(url_for('main.user_profile', username=username))

        current_user.unfollow(user)
        db.session.commit()
        flash(_('You are not following %(username)s.', username=username))
        return redirect(url_for('main.user_profile', username=username))

    return redirect(url_for('main.index'))


@bp.route('/search')
@login_required
def search():
    """View handles search form input. Returns posts satisfying the search"""

    if not g.search_form.validate():
        return redirect(url_for('main.explore'))

    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.text.data, page, app.config['POSTS_PER_PAGE'])

    next_url = None
    prev_url = None

    if total > page * app.config['POSTS_PER_PAGE']:
        next_url = url_for('main.search', text=g.search_form.q.data, page=page + 1)

    if page > 1:
        prev_url = url_for('main.search', text=g.search_form.text.data, page=page - 1)

    return render_template('main/search.html', title=_('Search'), posts=posts.all(),
                           next_url=next_url, prev_url=prev_url)


@bp.route('/user_profile/<username>/popup')
@login_required
def user_popup(username):
    """Popup to display user's info"""

    user = User.query.filter_by(username=username).first_or_404()
    form = SubmitForm()

    return render_template('main/user_popup.html', user=user, form=form)


@bp.route('/notifications')
@login_required
def notifications():
    """Returns notifications for the user: displays income messages number in real time"""

    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())

    return jsonify([
        {
            'name': notification.name,
            'data': notification.get_data(),
            'timestamp': notification.timestamp
        } for notification in notifications
    ])


@bp.route('/export_posts')
@login_required
def export_posts():
    """Exports posts for a user and sends to the email"""

    if current_user.get_task_in_progress('export_posts'):
        flash(_('An export task is currently in progress'))
    else:
        current_user.launch_task('export_posts', _('Exporting posts...'))
        db.session.commit()

    return redirect(url_for('main.user_profile', username=current_user.username))


@bp.before_request
def before_request():
    """Sets last seen date, local dates and search form for the user before the page request"""

    # Sets last_seen date
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()

    # Sets locale for dates on pages
    g.locale = str(get_locale())

app/messages/__init__.py
from flask import Blueprint

bp = Blueprint('messages', __name__)

from app.messages import routes

app/messages/routes.py
from datetime import datetime
from flask import flash, redirect, url_for, render_template, request
from flask_login import current_user, login_required
from flask_babel import _
from flask import current_app as app

from app import db
from app.messages import bp
from app.messages.forms import MessageForm
from app.models import User, Message


@bp.route('/send_message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    """Send Message View: sends private messages to the user"""

    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()

    if form.validate_on_submit():
        msg = Message(author=current_user, recipient=user, body=form.message.data)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.add(msg)
        db.session.commit()
        flash(_('Your message has been sent.'))
        return redirect(url_for('main.user_profile', username=recipient))

    return render_template('messages/send_message.html', title=_('Send Message'), form=form, recipient=recipient)


@bp.route('/messages')
@login_required
def messages():
    """Messages View: displays messages of and for the current user"""

    current_user.last_message_read_time = datetime.utcnow()
    current_user.add_notification('unread_message_count', 0)
    db.session.commit()
    page = request.args.get('page', 1, type=int)
    messages = current_user.messages_received.order_by(Message.timestamp.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)

    next_url = None
    prev_url = None

    if messages.has_next:
        next_url = url_for('messages.messages', page=messages.next_num)

    if messages.has_prev:
        prev_url = url_for('messages.messages', page=messages.prev_num)

    return render_template('messages/messages.html', title=_('Messages'), messages=messages.items, next_url=next_url,
                           prev_url=prev_url)

app/templates/main/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Edit Profile') }}</h1>

    <!-- Edit profile form -->
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>

{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- User greeting -->
{% block app_content %}
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>

    <!-- Form for post creating -->
    {% if form %}
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    {% endif %}

    <!-- Posts from users current user follows -->
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}

    <!-- Posts pagination -->
    {% include '_pagination.html' %}

{% endblock %}

app/templates/main/messages.html
{% extends "base.html" %}

{% block app_content %}

    <h1>{{ _('Messages') }}</h1>

    <!-- User's posts -->
    {% for post in messages %}
        {% include '_post.html' %}
    {% endfor %}

    <!-- Posts pagination -->
    {% include '_pagination.html' %}

{% endblock %}

app/templates/main/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Search Results') }}</h1>

    <!-- Posts from search result -->
    {% if posts %}
        {% for post in posts %}
            {% include '_post.html' %}
        {% endfor %}
    {% else %}
        <h4>{{ _('Results not found') }}</h4>
    {% endif %}

    <!-- Posts pagination -->
    {% include '_pagination.html' %}

{% endblock %}

app/templates/main/user_popup.html
<table class="table">
    <tr>

        <!-- Avatar -->
        <td width="64" style="border: 0;">
            <img src="{{ user.get_avatar(64) }}">
        </td>

        <td style="border: 0;">

            <!-- User info -->
            <p><a href="{{ url_for('main.user_profile', username=user.username) }}">
                {{ user.username }}</a>
            </p>

            <small>

                {% if user.about_me %}
                    <p>{{ user.about_me }}</p>
                {% endif %}

                {% if user.last_seen %}
                    <p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('lll') }}</p>
                {% endif %}

                <p>
                    {{ _('%(count)d followers', count=user.followers.count()) }},
                    {{ _('%(count)d following', count=user.followed.count()) }}
                </p>

                {% if user != current_user %}
                    {% if not current_user.is_following(user) %}

                    <!-- Follow / unfollow button -->
                    <p>
                        <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
                            {{ form.hidden_tag() }}
                            {{ form.submit(value=_('Follow'), class_='btn btn-default btn-sm') }}
                        </form>
                    </p>

                    {% else %}

                    <p>
                        <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
                            {{ form.hidden_tag() }}
                            {{ form.submit(value=_('Unfollow'), class_='btn btn-default btm-sm') }}
                        </form>
                    </p>

                    {% endif %}
                {% endif %}

            </small>
        </td>
    </tr>

</table>

app/templates/main/user_profile.html
{% extends "base.html" %}

{% block app_content %}
    <table>
        <tr valign="top">

            <!-- Avatar -->
            <td>
                <img src="{{ user.get_avatar(128) }}">
            </td>

            <!-- User info -->
            <td>
                <h1>{{ _('User: %(username)s', username=user.username) }}</h1>

                <!-- About me -->
                {% if user.about_me %}
                    <p>{{ user.about_me }}</p>
                {% endif %}

                <!-- Last seen -->
                {% if user.last_seen %}
                    <p>{{ _('Last seen: %(last_seen)s', last_seen=moment(user.last_seen).fromNow()) }}</p>
                {% endif %}

                <!-- Followers and following count -->
                <p>{{ _('%(followers)d followers, %(following)d following', followers=user.followers.count(),
                        following=user.followed.count()) }}</p>

                <!-- Link for profile edit -->
                {% if user == current_user %}
                    <p>
                        <a href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a>
                    </p>

                <!-- Export posts link -->
                {% if not current_user.get_task_in_progress('export_posts') %}
                    <p>
                        <a href="{{ url_for('main.export_posts') }}">
                            {{ _('Export your posts') }}
                        </a>
                    </p>
                {% endif %}

                <!-- Follow / unfollow button -->
                {% elif not current_user.is_following(user) %}
                    <p>
                    <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value= _('Follow')) }}
                    </form>
                    </p>
                {% else %}
                    <p>
                    <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value=_('Unfollow')) }}
                    </form>
                    </p>
                {% endif %}

                <!-- Send private message link -->
                {% if user != current_user %}
                    <p>
                        <a href="{{ url_for('messages.send_message', recipient=user.username) }}">
                        {{ _('Send private message') }}
                        </a>
                    </p>
                {% endif %}

            </td>
        </tr>
    </table>

    <!-- User's own posts -->
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}

    <!-- Posts pagination -->
    {% include '_pagination.html' %}

{% endblock %}